app = "gemini"
primary_region = "sin"

[[services]]
   auto_start_machines = true
   auto_stop_machines = "off" # ✅ 禁用自动停机
   force_https = true
   internal_port = 8000        # 或你的实际端口
   min_machines_running = 1

  [services.concurrency]
    type       = "connections"
    soft_limit = 99999
    hard_limit = 9999999999
