# fly.toml app configuration file generated for gemini-balance on 2025-04-21T09:14:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gemini-balance'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 4
  memory_mb = 8192
