app = "gemini"
primary_region = "sin"

[[services]]
  internal_port        = 8000
  protocol             = "tcp"
  force_https          = true
  auto_stop_machines   = "off"
  auto_start_machines  = true
  min_machines_running = 1

  [services.concurrency]
    type       = "connections"
    soft_limit = 99999
    hard_limit = 9999999999
